services:
  yq-runner:
    build: ./lang-runner
    security_opt:
      - seccomp:unconfined
    ports:
      - "3000:3000"
    volumes:
      - ./target/debug:/debug
    entrypoint: ['/debug/lang-runner']
  postgres:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: username # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: password # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: default_database # The PostgreSQL default database (automatically created at first launch)
    volumes:
      - ./postgres-data:/var/lib/postgresql/data


